---
title: "Data471 EDA Project"
author: "Group 21: Loren Whithair, Nancy Grace Busto, Hamid Mehmood, Leon Cai"
date: "`r Sys.Date()`"
output:
  pdf_document:
    md_extensions: -implicit_figures
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
```

```{=latex}
\setlength{\LTcapwidth}{\linewidth}
```

# Detailed Data Analysis

```{r detailed_analysis_libraries}
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r detailed_analysis_setup}

#----------------------
# Basic data setup (from group report)

lr.data <- read.csv(
  "data/2019/2019_Food_Access_Research_Atlas_Data/Food Access Research Atlas.csv",
  stringsAsFactors = FALSE,
  na.strings = c("NA", "NULL", "")
)

lr.data <- as_tibble(lr.data)

# Convert CensusTract to character:
lr.data$CensusTract <- as.character(lr.data$CensusTract)

# Convert Urban/Rural to factor, with Urban as reference
lr.data$Urban_f <- factor(lr.data$Urban, levels=c(1,0), labels = c("Urban", "Rural"))


# Response variable
lr.data$LILATracts_halfAnd10_f <- factor(lr.data$LILATracts_halfAnd10,
                                    levels=c(0,1),
                                    labels = c("Not low income/access", "Low income/access"))

# Relevant numerical variables
num_vars <- c(
  "Pop2010", "OHU2010",
  "PovertyRate", "MedianFamilyIncome", 
  "TractLOWI",
  "TractKids", "TractSeniors",
  "TractWhite", "TractBlack", "TractAsian", "TractNHOPI", "TractAIAN","TractOMultir", "TractHispanic"
)
for (v in num_vars) lr.data[[v]] <- as.numeric(lr.data[[v]])

# core_vars <- c("LA1and10", "PovertyRate", "MedianFamilyIncome", "Urban", "HUNVFlag")
# lr.data <- lr.data[complete.cases(lr.data[, core_vars]), ]

# compute populations as percentages
lr.data <- lr.data %>%
  mutate(
    TractLOWI_share = TractLOWI / Pop2010,
    TractKids_share = TractKids / Pop2010,
    TractSeniors_share = TractSeniors / Pop2010,
    TractWhite_share = TractWhite / Pop2010,
    TractBlack_share = TractBlack / Pop2010,
    TractAsian_share = TractAsian / Pop2010,
    TractNHOPI_share = TractNHOPI / Pop2010,
    TractAIAN_share = TractAIAN / Pop2010,
    TractOMultir_share = TractOMultir / Pop2010,
    TractHispanic_share = TractHispanic / Pop2010
  )

# compute populations as percentages
lr.data <- lr.data %>%
  mutate(
    TractLOWI_perc = TractLOWI_share * 100,
    TractKids_perc = TractKids_share * 100,
    TractSeniors_perc = TractSeniors_share * 100,
    TractWhite_perc = TractWhite_share * 100,
    TractBlack_perc = TractBlack_share * 100,
    TractAsian_perc = TractAsian_share * 100,
    TractNHOPI_perc = TractNHOPI_share * 100,
    TractAIAN_perc = TractAIAN_share * 100,
    TractOMultir_perc = TractOMultir_share * 100,
    TractHispanic_perc = TractHispanic_share * 100
  )

lr.data <- lr.data %>% mutate(
  l_TractSeniors_perc = log1p(TractSeniors_perc),
  l_TractKids_perc = log1p(TractKids_perc),
  l_TractWhite_perc = log1p(TractWhite_perc),
  l_TractBlack_perc = log1p(TractBlack_perc),
  l_TractHispanic_perc = log1p(TractHispanic_perc),
  l_TractAsian_perc = log1p(TractAsian_perc),
  l_TractNHOPI_perc = log1p(TractNHOPI_perc),
  l_TractAIAN_perc = log1p(TractAIAN_perc),
  l_TractOMultir_perc = log1p(TractOMultir_perc)
)

lr.data <- lr.data %>% 
  select(
    CensusTract, State, County,  # identifying info
    LILATracts_halfAnd10_f, LILATracts_halfAnd10, # response var
    # predictor + supporting vars
    Pop2010,
    Urban, Urban_f,
    ## demographic as total count
    TractLOWI, 
    TractKids, TractSeniors, 
    TractWhite, TractBlack, TractAsian, TractNHOPI, TractAIAN, TractOMultir, TractHispanic, 
    # demographics as percentages (out of 100)
    TractKids_perc, TractSeniors_perc, 
    TractWhite_perc, TractBlack_perc, TractAsian_perc, TractNHOPI_perc, TractAIAN_perc, TractOMultir_perc, TractHispanic_perc,
    
    # percentage demographics on logarithmic scale
    l_TractKids_perc, l_TractSeniors_perc, 
    l_TractWhite_perc, l_TractBlack_perc, l_TractAsian_perc, l_TractNHOPI_perc, l_TractAIAN_perc, l_TractOMultir_perc, l_TractHispanic_perc
  ) %>% 
  filter(
    !is.na(TractKids), 
    !(State %in% c("Hawaii", "Alaska")), # Hawaii and Alaska are distinct (geographically and culturally) 
    Pop2010 >= 150 # removes most extreme skews (percentage-based)
  ) 

lr.data.clean <- filter(lr.data, !(CensusTract %in% c(
  "4001942700", "48365950500" # abnormally large  demographic %s, Hispanic / AIAN
  ,"48341950200"
  )))
```

```{r model_build}
model <- glm(
  LILATracts_halfAnd10_f ~
    l_TractAsian_perc 
      * Urban_f
  + l_TractHispanic_perc 
      * Urban_f
  + l_TractNHOPI_perc 
      #* Urban_f
  + l_TractAIAN_perc 
      * Urban_f
  + l_TractOMultir_perc 
      * Urban_f
  + l_TractBlack_perc 
      # * TractKids_perc
      # * Urban_f
  + l_TractAsian_perc 
      # * TractKids_perc
      # * Urban_f
  + l_TractHispanic_perc 
      # * l_TractKids_perc 
      # * Urban_f
  
  , family="binomial"
  # , data=df
  , data=lr.data.clean # first lot of very clear outliers, based on abnormal demographic %s
)
```


```{r model_fit}
summary(model)
```

```{r resid}
plot(fit.l, which=1)
```
```{r fitted_vs_input}
# fit_v_input <- function(pred="")
#   
#   

```

# Conclusions and Recommendations

TODO


# References

Economic Research Service, U.S. Department of Agriculture. (2019).
*Food Access Research Atlas: Large Retailer Access Map (LRAM)
documentation*.
https://www.ers.usda.gov/data-products/food-access-research-atlas/documentation
